import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { getServerSession } from "next-auth";
import AppContext from "@/components/AppContext";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const session = getServerSession();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppContext session={session}>
            <Header />
            <main>{children}</main>
          </AppContext>
        </Providers>
      </body>
    </html>
  );
}
